apiVersion: v1
kind: Pod
metadata:
  name: app-node
  labels:
    app: app-node
spec:
  containers:
    - name: app-node
      image: devatron/tc-2023-repo:latest
      ports:
        - containerPort: 3333

      envFrom:
        - configMapRef:
            name: cm-app