apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  containers:
    - name: postgres-db
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:            
        - name: POSTGRES_DB
          value: "pedidos_db"
        - name: POSTGRES_USER
          value: "docker"
        - name: POSTGRES_PASSWORD
          value: "docker"
      volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql
  volumes:
    - name: data
      emptyDir: {}
