apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vc-postgres-db
  labels:
    app: postgres-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi