name: kubernetes

on:
  workflow_dispatch:
  
env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1  
permissions:
  contents: read
      
jobs:
  EKS:
    name: Deploy AWS EKS
    runs-on: ubuntu-latest   
      
    steps:    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.aws.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
