name: Main

on:  
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  docker:    
    uses: ./.github/workflows/docker.yaml
    secrets: inherit

  infra:
    needs: docker    
    uses: ./.github/workflows/infra-google.yaml
    secrets: inherit
